3.3.x test tweaks
phalcon/incubator pull request #853
Opened 2018-02-18 03:36 UTC by Fenikkusu

Hello!

* Type: bug fix | new feature | code quality

**In raising this pull request, I confirm the following (please check boxes):**

- [ ] I have read and understood the [Contributing Guidelines](https://github.com/phalcon/incubator/blob/master/CONTRIBUTING.md)?
- [ ] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:
A couple items going on here (One thing lead to another). First, I've renamed each codeception yaml to .dist.yaml and added the existing ones to the .gitignore. This allows us to override the default yamls without having to worry about not committing them (IE: I can add populate: true for testing the db module). Second, I corrected a misnamed drop tables. Third, I added a docker-compose.yml file that can be used with local testing. Finally (and the primary reason), I have made some slight changes to the ModelTestCase::setDb Method. The instance of change was due to the new testing I added and allows a child class of the passed name to work instead of just the exact class. Additionally, I added the ability to default the config to $this->getConfig() in the case $this->config has not yet been set. This makes it easier to add config settings. I also added a slight change to allow the setDb to default to the db config entry flat out if the adapter isn't set.

Thanks

2018-02-18 08:34 UTC, sergeyklay requested changes
We don't add changes directly to stable branches or `master`. Could you please send this PR to the `3.3.x` branch?

2018-02-18 08:34 UTC, sergeyklay commented on tests/unit/Test/Traits/ModelTestCaseTest.php
> + */
Could you remove this

2018-02-18 08:34 UTC, sergeyklay commented on docker-compose.yml
> +        image: "tutum/mongodb"
Could we use official image here?

2018-02-18 16:29 UTC, Fenikkusu commented on docker-compose.yml
> +        image: "tutum/mongodb"
Originally I was unable to figure out how to get the official image to create the correct DB. After some additionally digging I was able to find an undocumented method to use the official repo.

2018-02-18 16:29 UTC, Fenikkusu commented
Updates Applied.

2018-02-18 16:44 UTC, sergeyklay requested changes
@Fenikkusu Looks good to me. Could you please amend README.md (https://github.com/phalcon/incubator/blob/master/tests/README.md) to add instruction about ignored Codeception's suites.

2018-02-18 16:46 UTC, sergeyklay commented on tests/_data/dump.sql
> -DROP TABLE if EXISTS `session`;
👍

2018-02-19 03:19 UTC, Fenikkusu commented
I've updated the README.md file with both details about docker-compose and the advanced configuration. I wasn't sure if you wanted me to directly mention the ignored files or not. I personally didn't see a reason to directly mention the ignored files and instead opted for a 'you can also do this' type approach.

2018-02-20 11:29 UTC, sergeyklay approved these changes
Looks good to me

2018-02-20 11:30 UTC, merged

2018-02-20 11:30 UTC, sergeyklay commented
Thank you